sonar.projectKey=prj-next
sonar.projectName=prj-next
sonar.projectVersion=1.0
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.login=squ_aaa59ea59ddf29151f6a2b86b3819f18882fce8c
sonar.branch.name=main
sonar.issues_in_sandbox.skip=true
sonar.new_issues_in_sandbox.skip=true