name: SonarQube Analysis

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-cache
          restore-keys: |
            ${{ runner.os }}-sonar-cache

      - name: SonarQube Scan (Branch)
        if: github.event_name == 'push'
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: -Dsonar.scanner.skipJreProvisioning=true
        with:
          args: >
            -Dsonar.projectKey=prj-next
            -Dsonar.projectName=prj-next
            -Dsonar.sources=src
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.issues_in_sandbox.skip=true
            -Dsonar.new_issues_in_sandbox.skip=true
            -Dsonar.scanner.downloadPlugins=false

      - name: SonarQube Scan (Pull Request)
        if: github.event_name == 'pull_request'
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: -Dsonar.scanner.skipJreProvisioning=true
        with:
          args: >
            -Dsonar.projectKey=prj-next
            -Dsonar.projectName=prj-next
            -Dsonar.sources=src
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.issues_in_sandbox.skip=true
            -Dsonar.new_issues_in_sandbox.skip=true
            -Dsonar.scanner.downloadPlugins=false