name: SonarQube Analysis

permissions:
  contents: read

on:
  push:
    branches:
      - develop
  

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: -Dsonar.scanner.skipJreProvisioning=true
        with:
          args: >
            -Dsonar.branch.name=${{ github.ref_name }}